# docker-compose.yml
services:
  database:
    build: ./database
    env_file:
      - .env
    volumes:
      - ./database/dnd_game.db:/app/dnd_game.db
    restart: always

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: always

  webapp:
    build:
      context: .
      dockerfile: ./webapp/Dockerfile
    env_file:
      - .env
    ports:
      - "8502:8501"   # L'app écoute sur 8501, accessible sur le port 8502 de l'hôte
    depends_on:
      - api
    restart: always
